### ISSUE TITLE
Add option to use 'me' in title attributes

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/on_the_web#11]
Currently you can check a box to use the site name in title attributes, or uncheck it to use 'us' instead.

E.g.:
'Find [SITE_NAME] on Facebook'
'Find us on Facebook'

I'd like an option to use 'me' instead:
'Find me on Facebook'

This'd make it good for blogs, etc.

**Comment by jenlampton** [comment]
Yep, great idea!
