### ISSUE TITLE
Add Last.fm icon

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/on_the_web#13]
https://www.last.fm/about/resources

**Comment by jenlampton** [comment]
Thanks! None of those icons are going to work as they aren't square, and don't really match the asthetic of the current icon set. 

If we wait, and instead add this to the 2.x branch we won't need an image icon, we'll only need http://fontawesome.io/icon/lastfm-square/

Adding milestone.

**Comment by jenlampton** [comment]
Committed a LastFM service.
