### ISSUE TITLE
Add support for both -square and non -square versions of icons

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/on_the_web#21]
Spin off from https://github.com/backdrop-contrib/on_the_web/issues/20

**Comment by ghost** [comment]
I like the idea of choosing the type of icon to show, and I don't think it really matters that -square versions won't exist for every type straight away - just show the non-square version by default.

**Comment by jenlampton** [comment]
Yeah, the more I think about it I like that idea too.

**Comment by jenlampton** [comment]
I've also added a follow-up commit to include two missing square icons :) closing.
