### ISSUE TITLE
Support v5 of FontAwesome

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/on_the_web#22]
FontAwesome now has a v5, which I've just updated the BD FontAwesome module to support. A few small changes are needed to add support here too.

**Comment by ghost** [comment]
I'm having trouble making a PR, so here's a patch instead...
[on_the_web-support-fontawesome-v5.txt](https://github.com/backdrop-contrib/on_the_web/files/1595607/on_the_web-support-fontawesome-v5.txt)

**Comment by ghost** [comment]
Got it!

**Comment by jenlampton** [comment]
Excellent, thank you!  I reverted the changes from `-square` to regular icons, since I'd like to switch all the icons over at once, when that new setting is added in https://github.com/backdrop-contrib/on_the_web/issues/21. But I've merged the other changes :)
