### ISSUE TITLE
Icons Missing in 1.x-2.x Branch

### ISSUE THREAD

**Issue by prevoj** [backdrop-contrib/on_the_web#27]
I just recently installed on_the_web and the icons didn't show up in the block. It turns out that it looks like you missed or deleted the images folder in the latest branch. I had never installed the original version, only the latest one so I didn't get the images installing the latest branch from inside of Backdrop. I grabbed the images folder tree from the original branch, copied it to the web site under your module's folder and then they showed up fine.

**Comment by prevoj** [comment]
On The Web auto updated to 1.x-1.7.1 on my site and when it did because the images are missing from that kit, it deleted the images folder from my web site's On The Web folder tree and all the images are missing. I prefer the look of the images over the font.

Can you tell me if the images are going away as an option? If so, you need to remove them as an option from the configuration screen. If not, please add the images folder back to your distribution so you don't keep breaking my site. Thanks.

**Comment by jenlampton** [comment]
> Can you tell me if the images are going away as an option?

yes, that is the long term plan. New, matching, Open Source image icons are nearly impossible to source.

> If so, you need to remove them as an option from the configuration screen.

Hm. I'm not sure what the intent was here. Maybe there is supposed to be a way for you to define an image location? It definitely seems broken the way it is currently.

> If not, please add the images folder back to your distribution so you don't keep breaking my site.

Yep, I'll add the images back to the branch for now. We definitely need a cleaner upgrade path before they can go away entirely.

Thank you for opening this issue.

**Comment by jenlampton** [comment]
Committed the images back, they will be in the next release.

**Comment by prevoj** [comment]
Thanks! I totally understand. We deal with fonts and icons and licensing is a total nightmare!
