### ISSUE TITLE
Add link/icon for GitHub profile

### ISSUE THREAD

**Issue by sutibun** [backdrop-contrib/on_the_web#3]
Minor feature request.

How about adding support for both
- GitHub profile

**Comment by jenlampton** [comment]
Yep, I was just wanting github myself!  Do you have any suggestions as to where to get an Open Source icon for each?

**Comment by klonos** [comment]
> ...any suggestions as to where to get an Open Source icon for each?

GitHub: https://octicons.github.com/icon/mark-github/

Periscope ???

**Comment by jenlampton** [comment]
I forgot that I can't add it to 1.x without an icon. Opening and setting milestone for 2.x.

**Comment by jenlampton** [comment]
Okay, added to 12.x branch now instead.
