### ISSUE TITLE
Add new icon for email/contact/newsletter

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/on_the_web#30]
Add a new icon for a newsletter (icon suggestions welcome!)

Suggested icons:
* FontAwesome envelope: https://fontawesome.com/icons/envelope?s=solid&f=classic
* FontAwesome envelope-square https://fontawesome.com/icons/envelope-square?s=solid&f=classic
* Fork Awesome envelope https://forkaweso.me/Fork-Awesome/icon/envelope/
* Fork Awesome envelope-square https://forkaweso.me/Fork-Awesome/icon/envelope-square

**Comment by laryn** [comment]
Or an email/contact us link? (Maybe an envelope could be used for either of these purposes)

**Comment by jenlampton** [comment]
The option and icon has been added, and will be available in the next release.
