### ISSUE TITLE
Switch to using an icon font (fontawesome) for icons.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/on_the_web#6]
Finding open-source icons for various platforms is a long-standing issue for this module. I'd like to switch to using an icon font (specifically font-awesome) so that all the icons that are available there are also available here.

**Comment by ghost** [comment]
You could depend on the [Font Awesome](https://github.com/backdrop-contrib/font_awesome) module...

**Comment by jenlampton** [comment]
I'd thought of that, but I generally dislike dependency chains. Maybe check for the module, and if not there, load fontawesome from CDN?

**Comment by ghost** [comment]
That'd work.

**Comment by ghost** [comment]
There you go!
