### ISSUE TITLE
Remove myspace

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/on_the_web#8]
no icon in font awesome, how relevant can they still be?

**Comment by ghost** [comment]
I see you already posted here yourself, but in case others are interested: https://github.com/FortAwesome/Font-Awesome/issues/831

**Comment by ghost** [comment]
Whatever is decided here might also apply to iTunes, as it's yet to get a Font Awesome icon too: https://github.com/FortAwesome/Font-Awesome/issues/919
